controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
    
mylaw_home:
    resource: ../../src/Controller/routing.yaml
    
