index:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::index' }
    
settings:
    path: /settings
    defaults: { _controller: 'App\Controller\SettingsController::index' }
    
settings_password_change:
    path: /settings/password
    defaults: { _controller: 'App\Controller\SettingsController::passwordChange' }
    
user_table_dashboard:
    path: /tables/{table_name}
    defaults: { _controller: 'App\Controller\TableController::index' }
    
user_table_search:
    path: /tables/search/{table_name}
    defaults: { _controller: 'App\Controller\TableController::search' }
    
user_table_create_edit:
    path: /tables/edit/{table_name}
    defaults: { _controller: 'App\Controller\TableController::createEdit' }
  
user_table_delete:
    path: /tables/delete/{table_name}
    defaults: { _controller: 'App\Controller\TableController::delete' }
    
user_login:
    path: /login
    defaults: { _controller: 'App\Controller\HomeController::login' }

user_admin_home:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::index' }

user_check:
    path: /check
    
user_logout:
    path: /logout