index:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::index' }
    
user_login:
    path: /login
    defaults: { _controller: 'App\Controller\HomeController::index' }

user_admin_home:
    path: /admin/home
    defaults: { _controller: 'App\Controller\HomeController::index' }
user_check:
    path: /admin/check
    
user_logout:
    path: /admin/logout