index:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::index' }
    
settings:
    path: /settings
    defaults: { _controller: 'App\Controller\SettingsController::index' }
    
settings_password_change:
    path: /settings/password
    defaults: { _controller: 'App\Controller\SettingsController::passwordChange' }
    
user_login:
    path: /login
    defaults: { _controller: 'App\Controller\HomeController::login' }

user_admin_home:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::index' }

user_check:
    path: /check
    
user_logout:
    path: /logout